In [19]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_score, recall_score, auc, roc_auc_score

In [3]:
df = pd.read_csv('candy-data.csv')
df

,competitorname,chocolate,fruity,caramel,peanutyalmondy,nougat,crispedricewafer,hard,bar,pluribus,sugarpercent,pricepercent,winpercent,Y
0,100 Grand,1,0,1,0,0,1,0,1,0,0.732,0.860,66.971725,1
1,3 Musketeers,1,0,0,0,1,0,0,1,0,0.604,0.511,67.602936,1
2,One dime,0,0,0,0,0,0,0,0,0,0.011,0.116,32.261086,0
3,One quarter,0,0,0,0,0,0,0,0,0,0.011,0.511,46.116505,0
4,Air Heads,0,1,0,0,0,0,0,0,0,0.906,0.511,52.341465,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,Snickers Crisper,1,0,1,1,0,1,0,1,0,0.604,0.651,59.529251,1
66,Sour Patch Kids,0,1,0,0,0,0,0,0,1,0.069,0.116,59.863998,1
67,Sour Patch Tricksters,0,1,0,0,0,0,0,0,1,0.069,0.116,52.825947,1
68,Starburst,0,1,0,0,0,0,0,0,1,0.151,0.220,67.037628,1
69,Strawberry bon bons,0,1,0,0,0,0,1,0,1,0.569,0.058,34.578991,0

In [9]:
test = pd.read_csv('candy-test.csv')
X_test = test[['chocolate', 'fruity', 'caramel', 'peanutyalmondy', 'nougat', 
                   'crispedricewafer', 'hard', 'bar', 'pluribus', 'sugarpercent', 'pricepercent']]
y_test = test['Y']

In [11]:
test

,competitorname,chocolate,fruity,caramel,peanutyalmondy,nougat,crispedricewafer,hard,bar,pluribus,sugarpercent,pricepercent,Y
0,Sugar Babies,0,1,1,0,0,0,1,0,1,0.647364,0.76700,0
1,Sugar Daddy,1,0,0,0,1,0,1,0,0,0.418000,0.32500,0
2,Super Bubble,0,1,0,0,0,0,0,0,0,0.162000,0.11600,0
3,Swedish Fish,0,1,0,0,0,0,0,0,1,0.604000,0.75500,1
4,Tootsie Pop,1,0,0,0,0,0,0,0,0,0.876560,0.56540,1
5,Tootsie Roll Juniors,1,0,0,0,0,0,0,0,0,0.313000,0.51100,0
6,Tootsie Roll Midgies,1,0,0,0,0,0,0,0,1,0.174000,0.01100,0
7,Tootsie Roll Snack Bars,1,0,0,0,0,0,0,1,0,0.465000,0.32500,1
8,Trolli Sour Bites,0,1,0,0,0,0,0,0,1,0.313000,0.25500,0
9,Twix,0,1,0,0,0,0,0,0,0,0.735430,0.86634,1
10,Twizzlers,0,1,0,0,0,0,0,0,0,0.220000,0.11600,0
11,Warheads,0,1,0,0,0,0,1,0,0,0.093000,0.11600,0
12,Welchs Fruit Snacks,0,1,0,0,0,0,0,0,1,0.313000,0.31300,0
13,Werthers Original Caramel,1,0,1,0,0,0,1,0,0,0.186000,0.26700,0
14,Whoppers,1,0,0,0,0,0,0,0,1,0.872000,0.84800,1

In [4]:
train_df = df[(df['competitorname'] != 'Mike & Ike') & (df['competitorname'] != 'Root Beer Barrels') \
              & (df['competitorname'] != 'Starburst')]

In [5]:
X_train = train_df[['chocolate', 'fruity', 'caramel', 'peanutyalmondy', 'nougat', 
                   'crispedricewafer', 'hard', 'bar', 'pluribus', 'sugarpercent', 'pricepercent']]
y_train = train_df['Y']

In [8]:
mdl = LogisticRegression(random_state = 2019, solver = 'lbfgs').fit(X_train, y_train)

In [13]:
mdl.predict_proba(X_test)[7]

array([0.21929811, 0.78070189])

In [26]:
precision_score(y_test, mdl.predict(X_test))

0.5

In [27]:
recall_score(y_test, mdl.predict(X_test))

0.6

In [30]:
roc_auc_score(y_test, mdl.predict_proba(X_test)[:, 1])

0.8799999999999999